version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: taxifleet_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taxifleetdb
      - POSTGRES_MULTIPLE_DATABASES=taxifleetdb,taxifleetdb_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh

  api:
    container_name: taxifleet_api
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taxifleetdb
      - TEST_DATABASE_URL=postgresql://user:password@db:5432/taxifleetdb_test
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  postgres_data:

